server:
  port: 7012
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.196.47:3306/forum?serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/**/**/**/*.xml
logging:
  config: /HL/IdeaProjects/SpringBoot-Item/springboot-slf4j/src/main/resources/logback.xml
  level:
    com.hl.magic: trace